language: clojure
lein: lein2
script: bash ./deploy.sh
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8

script:
  - bash ./build.sh

env:
  global:
    - GITHUB_REF: github.com/HealthSamurai/videorecorder-demo
